# Generated by Django 5.1.2 on 2024-10-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovimentacaoEstoque',
            new_name='Movimentacao',
        ),
    ]
