# Generated by Django 5.1.2 on 2024-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('carne', 'Carne'), ('tempero', 'Tempero'), ('acompanhamento', 'Acompanhamento'), ('bebida', 'Bebida')], max_length=50),
        ),
    ]
